Commencement.Mvc/Controllers/PetitionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Commencement.Controllers.Filters;
using Commencement.Controllers.Services;
using Commencement.Controllers.ViewModels;
using Commencement.Core.Domain;
using Commencement.Core.Helpers;
using Commencement.Core.Resources;
using MvcContrib;
using Serilog;

namespace Commencement.Controllers
{
    
    public class PetitionController : ApplicationController
    {
        private readonly IEmailService _emailService;
        private readonly ICeremonyService _ceremonyService;
        private readonly IPetitionService _petitionService;
        private readonly IErrorService _errorService;


        public PetitionController(IEmailService emailService, ICeremonyService ceremonyService, IPetitionService petitionService, IErrorService errorService)
        {
            _emailService = emailService;
            _ceremonyService = ceremonyService;
            _petitionService = petitionService;
            _errorService = errorService;
        }

        //
        // GET: /Petition/
        /// <summary>
        /// #1
        /// </summary>
        /// <returns></returns>
        [AnyoneWithRole]
        public ActionResult Index()
        {
            return View();
        }

        #region Extra Ticket Petitions
        /// <summary>
        /// #2
        /// </summary>
        /// <param name="ceremonyId"></param>
        /// <returns></returns>
        [AnyoneWithRole]
        public ActionResult ExtraTicketPetitions(int? ceremonyId, bool? viewAll)
        {
            var viewModel = AdminExtraTicketPetitionViewModel.Create(Repository, _ceremonyService, _petitionService, CurrentUser, TermService.GetCurrent(), ceremonyId, viewAll);
            return View(viewModel);
        }

        /// <summary>
        /// #3
        /// </summary>
        /// <param name="id"></param>
        /// <param name="isApproved"></param>
        /// <returns></returns>
        [HttpPost]
        [AnyoneWithRole]
        public JsonResult DecideExtraTicketPetition(int id /* Registration Participation Id */, bool isApproved)
        {
            var participation = Repository.OfType<RegistrationParticipation>().GetNullableById(id);

            if (participation == null) return Json("Could not find registration.");
            if (participation.ExtraTicketPetition == null) return Json("Could not find extra ticket petition.");
            if (!_ceremonyService.HasAccess(participation.Ceremony.Id, CurrentUser.Identity.Name)) return Json("You do not have access to that ceremony.");

            var petition = participation.ExtraTicketPetition;
            petition.MakeDecision(isApproved);

            Repository.OfType<ExtraTicketPetition>().EnsurePersistent(petition);

  
            try
            {
                _emailService.QueueExtraTicketPetitionDecision(participation);
            }
            catch (Exception ex)
            {
                Log.Error(ex, "Error creating email queue for Petition Controller QueueExtraTicketPetitionDecision-1: {ex}", ex);
                _errorService.ReportError(ex);
            }



            return Json(string.Empty);
        }

        /// <summary>
        /// #4
        /// </summary>
        /// <param name="id"></param>
        /// <param name="tickets"></param>
        /// <param name="streaming"></param>
        /// <returns></returns>
        [AnyoneWithRole]
        [HttpPost]
        public JsonResult UpdateTicketAmount(int id /* Registration Participation Id */, int tickets, bool streaming)
        {
            var participation = Repository.OfType<RegistrationParticipation>().GetNullableById(id);

            if (participation == null) return Json(new UpdateTicketModel(null, "Could not locate registration."));

            var petition = participation.ExtraTicketPetition;
            var ceremony = participation.Ceremony;

            if (petition == null) return Json(new UpdateTicketModel(ceremony, "Could not find petition."));
            if (ceremony == null) return Json(new UpdateTicketModel(ceremony,"Could not find ceremony."));
            if (!_ceremonyService.HasAccess(ceremony.Id, CurrentUser.Identity.Name)) return Json(new UpdateTicketModel(ceremony, "You do not have access to ceremony."));
            if (!petition.IsPending) return Json(new UpdateTicketModel(ceremony, "Petition is not pending"));

            if (streaming) petition.NumberTicketsStreaming = tickets > 0 ? tickets : 0;
            else petition.NumberTickets = tickets > 0 ? tickets : 0;

            Repository.OfType<ExtraTicketPetition>().EnsurePersistent(petition);

            return Json(new UpdateTicketModel(ceremony, string.Empty));
        }

        /// <summary>
        /// #5
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [AnyoneWithRole]
        [HttpPost]
        public RedirectToRouteResult ApproveAllExtraTicketPetition(int id /* Ceremony Id */)
        {
            var ceremonies = _ceremonyService.GetCeremonies(CurrentUser.Identity.Name);
            var ceremony = ceremonies.SingleOrDefault(a => a.Id == id);

            // ceremony not found or user does not have access, redirect to the page so they can select a valid ceremony
            if (ceremony == null) return this.RedirectToAction(a => a.ExtraTicketPetitions(null, null));
            if (!_ceremonyService.HasAccess(ceremony.Id, CurrentUser.Identity.Name))
            {
                Message = "You do not have rights to that ceremony";
                return this.RedirectToAction(a => a.ExtraTicketPetitions(null, null));
            }
            // load up all pending extra ticket petitions
            var participations = _petitionService.GetPendingExtraTicket(CurrentUser.Identity.Name, ceremony.Id);

            var totalCount = 0;
            var ticketCount = 0;
            var streamingCount = 0;

            // approve all
            foreach (var a in participations)
            {
                a.ExtraTicketPetition.MakeDecision(true);           // make the decision information
                
                try
                {
                    _emailService.QueueExtraTicketPetitionDecision(a);  // queue the email for the decision
                }
                catch (Exception ex)
                {
                    Log.Error(ex, "Error creating email queue for Petition Controller QueueExtraTicketPetitionDecision-2: {ex}", ex);
                    _errorService.ReportError(ex);
                }
                Repository.OfType<ExtraTicketPetition>().EnsurePersistent(a.ExtraTicketPetition);

                totalCount++;
                ticketCount += a.ExtraTicketPetition.NumberTickets.HasValue ? a.ExtraTicketPetition.NumberTickets.Value : 0;
                streamingCount += a.ExtraTicketPetition.NumberTicketsStreaming.HasValue ? a.ExtraTicketPetition.NumberTicketsStreaming.Value: 0;
            }

            Message = string.Format("You have successfully approved {0} with a total of {1} regular tickets", totalCount, ticketCount);
            if (ceremony.HasStreamingTickets) Message += string.Format(" and a total of {0} streaming tickets.", streamingCount);
            else Message += ".";

            return this.RedirectToAction(a => a.ExtraTicketPetitions(id, null));
        }
        #endregion

        #region Registration Petitions
        /// <summary>
        /// #6
        /// </summary>
        /// <returns></returns>
        [AnyoneWithRole]
        public ActionResult RegistrationPetitions()
        {
            var viewModel = AdminPetitionsViewModel.Create(Repository, _ceremonyService, _petitionService, CurrentUser.Identity.Name, TermService.GetCurrent());
            return View(viewModel);
        }

        /// <summary>
        /// #7
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [AnyoneWithRole]
        public ActionResult RegistrationPetition(int id)
        {
            var registrationPetition = Repository.OfType<RegistrationPetition>().GetNullableById(id);
            if (registrationPetition == null)
            {
                Message = "Unable to find registration petition.";
                return this.RedirectToAction(a => a.Index());
            }

            if (!_ceremonyService.HasAccess(registrationPetition.Ceremony.Id, CurrentUser.Identity.Name))
            {
                Message = "You do not have rights to that ceremony";
                return this.RedirectToAction(a => a.ExtraTicketPetitions(null, null));
            }

            return View(registrationPetition);
        }

        /// <summary>
        /// #8
        /// </summary>
        /// <param name="id"></param>
        /// <param name="isApproved"></param>
        /// <returns></returns>
        [HttpPost]
        [AnyoneWithRole]
        public ActionResult DecideRegistrationPetition(int id, bool isApproved)
        {
            var registrationPetition = Repository.OfType<RegistrationPetition>().GetNullableById(id);
            if (registrationPetition == null)
            {
                Message = "Petition not found.";
                return this.RedirectToAction<ErrorController>(a => a.Index());
            }
            if (!_ceremonyService.HasAccess(registrationPetition.Ceremony.Id, CurrentUser.Identity.Name))
            {
                Message = "You do not have rights to that ceremony";
                return this.RedirectToAction(a => a.ExtraTicketPetitions(null, null));
            }
            var registration = registrationPetition.Registration;

            // set the decision

Commencement.Mvc/Views/Petition/ExtraTicketPetition.cshtml
@using Commencement.Core.Helpers
@model Commencement.MVC.Controllers.ViewModels.ExtraTicketPetitionModel

@{
    ViewBag.Title = "ExtraTicketPetitionNew";
    Layout = "~/Views/Shared/_StudentLayout.cshtml";

    var registrations = Model.Registration.RegistrationParticipations.Where(x => !x.Cancelled).ToList();
    var counter = 0;
}

@section NavButtons
{
    <div class="pull-right">
        @Html.Partial("_LogonPartial")
    </div>
}

<div class="banner banner--register">
    <div class="banner_contents">
        <img src="@Url.Content("~/Images/Media/commencement_welcome.svg")" alt="">
    </div>
</div>

<div class="studentbar">
    <div class="studentbar__contents">
        <div class="studentbar--item">
            <p><b>Name:</b> @Model.Registration.Student.FullName</p>
        </div>
        <div class="studentbar--item">
            <p><b>Email:</b> @Model.Registration.Student.Email</p>
        </div>
        <div class="studentbar--item">
            <p><b>Student ID:</b> @Model.Registration.Student.StudentId</p>
        </div>
        <div class="studentbar--item">
            <p><b>Units:</b> @Model.Registration.Student.TotalUnits</p>
        </div>
        <div class="studentbar--item">
            <p><b>Major(s):</b> @Model.Registration.Student.ActualStrMajors</p>
        </div>
    </div>
</div>

@using (Html.BeginForm("ExtraTicketPetition", "Petition", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="main">
        <div class="main_contents">
            <div class="register">
                <div class="register__section">
                    @Html.ValidationSummary("Please correct all errors below")
                    @for (int j = 0; j < registrations.Count; j++)
                    {
                        var participation = registrations[j];

                        <div class="ceremony">
                            <h2>@participation.Ceremony.CeremonyName</h2>
                            @if (!Model.AvailableParticipationIds.Contains(participation.Id))
                            {
                                var theAlertMessage = string.Empty;
                                if (participation.ExtraTicketPetition != null)
                                {
                                    theAlertMessage = "This ceremony is not available for extra ticket petition because you have previously submitted a petition.";
                                }
                                else if (DateTime.UtcNow.ToPacificTime() < participation.Ceremony.ExtraTicketBegin) //TODO: Fix Date for UTC
                                {
                                    theAlertMessage = string.Format("This ceremony is not available for extra ticket petition.  Please return on {0:d} to submit a petition.", participation.Ceremony.ExtraTicketBegin);
                                }
                                else if (DateTime.UtcNow.ToPacificTime() > participation.Ceremony.ExtraTicketDeadline.AddDays(1)) //TODO: Fix date for UTC
                                {
                                    theAlertMessage = string.Format("This ceremony is not available for extra ticket petitions.  The deadline was on {0:d} ", participation.Ceremony.ExtraTicketDeadline);
                                }
                                <div class="alert alert-danger">
                                    <span>@theAlertMessage</span>
                                </div>
                            }

                            <table cellspacing="10">
                                <tbody>
                                <tr>
                                    <td><b>Major:</b></td>
                                    <td>@Html.DisplayFor(x => participation.Major.Name)</td>
                                </tr>
                                <tr>
                                    <td><b>Ceremony Time:</b></td>
                                    <td>@Html.DisplayFor(x => participation.Ceremony.DateTime)</td>
                                </tr>
                                <tr>
                                    <td><b>Delivery Method:</b></td>
                                    <td>@Html.DisplayFor(x => participation.TicketDistributionMethod.Name)</td>
                                </tr>
                                <tr>
                                    <td><b># Tickets Requested:</b></td>
                                    <td>@Html.DisplayFor(x => participation.NumberTickets)</td>
                                </tr>
                                @if (Model.AvailableParticipationIds.Contains(participation.Id))
                                {
                                    var postModel = Model.ExtraTicketPetitionPostModels.Where(a => a.RegistrationParticipation == participation).FirstOrDefault();                                    

                                    @Html.Hidden(string.Format("extraTicketPetitions[{0}].Ceremony", counter), participation.Ceremony.Id)
                                    @Html.Hidden(string.Format("extraTicketPetitions[{0}].RegistrationParticipation", counter), participation.Id)

                                    <tr>
                                        <td><b>Extra Tickets:</b></td>
                                        <td>
                                            <select id="@string.Format("extraTicketPetitions[{0}]_NumberTickets", counter)" name="@string.Format("extraTicketPetitions[{0}].NumberTickets", counter)" class="long">

                                                <option value="">--Select # of Tickets--</option>

                                                @for (int i = 1; i <= participation.Ceremony.ExtraTicketPerStudent; i++)
                                                {
                                                    <option value="@i" @(postModel != null && i == postModel.NumberTickets ? "selected=\"selected\"" : string.Empty)>@string.Format("{0:00}", i)</option>
                                                }
                                            </select>
                                        </td>
                                    </tr>
                                    if (participation.Ceremony.HasStreamingTickets)
                                    {
                                        <tr>
                                            <td><b>Streaming Tickets:</b></td>
                                            <td>
                                                <select id="@string.Format("extraTicketPetitions[{0}]_NumberStreamingTickets", counter)" name="@string.Format("extraTicketPetitions[{0}].NumberStreamingTickets", counter)" class="long">

                                                    <option value="">--Select # of Tickets--</option>

                                                    @for (int i = 1; i <= participation.Ceremony.ExtraTicketPerStudent; i++)
                                                    {
                                                        <option value="@i" @(postModel != null && i == postModel.NumberStreamingTickets ? "selected=\"selected\"" : string.Empty)>@string.Format("{0:00}", i)</option>
                                                    }
                                                </select>
                                            </td>
                                        </tr>
                                    }
                                    else
                                    {
                                        @Html.Hidden(string.Format("extraTicketPetitions[{0}]_NumberStreamingTickets", counter), 0)
                                    }

                                }


                                </tbody>
                            </table>
                            @if (Model.AvailableParticipationIds.Contains(participation.Id))
                            {
                                <div class="input__group">
                                    <label class="pull-left">Reason</label>
                                    <textarea style="width: 100%" type="text" id="@string.Format("extraTicketPetitions[{0}].Reason", counter)" name="@string.Format("extraTicketPetitions[{0}].Reason", counter)" rows="4" class="petition-reason">@(participation.ExtraTicketPetition != null ? participation.ExtraTicketPetition.Reason : string.Empty)</textarea>
                                    @Html.ValidationMessage("Reason" + participation.Ceremony.Id)
                                </div>
                                counter++;
                            }
                        </div>

                    }
                    <button type="submit" class="btn btn-18 btn-green"><i class="fa fa-graduation-cap" aria-hidden="true"></i> Submit </button>
                    <a href="@Url.Action("DisplayRegistration", "Student")" class="btn btn-18 btn-blue">Cancel</a>
                </div>


            </div>

        </div>

    </div>


}


@section AdditionalScripts
{
    @Scripts.Render("~/bundles/easycounter")
    @Scripts.Render("~/bundles/jqueryval")   
    <script type="text/javascript" src="https://ajax.aspnetcdn.com/ajax/mvc/4.0/jquery.validate.unobtrusive.min.js"></script>

    @*TODO: Fix jquery multiple loads. page validate isn't working would these*@
    <script>
        $(function () {
            $("textarea.petition-reason")
                .jqEasyCounter({
                    'maxChars': 100,
                    'maxCharsWarning': 80,
                    'msgAppendMethod': 'insertBefore',
                    'msgTextAlign': 'right'
                });
        });
    </script>
    


}


Commencement.Mvc/Views/Petition/ExtraTicketPetitionNew.cshtml
@model Commencement.Controllers.ViewModels.ExtraTicketPetitionModel

@{
    ViewBag.Title = "ExtraTicketPetitionNew";
    Layout = "~/Views/Shared/_StudentLayout.cshtml";

    var registrations = Model.Registration.RegistrationParticipations.Where(x => !x.Cancelled).ToList();
    var counter = 0;
}

<div class="pull-right">
    @Html.Partial("_LogonPartial")
</div>

<div class="banner banner--register">
    <div class="banner_contents">
        <img src="@Url.Content("~/Images/Media/commencement_welcome.svg")" alt="">
    </div>
</div>

<div class="studentbar">
    <div class="studentbar__contents">
        <div class="studentbar--item">
            <p><b>Name:</b> @Model.Registration.Student.FullName</p>
        </div>
        <div class="studentbar--item">
            <p><b>Email:</b> @Model.Registration.Student.Email</p>
        </div>
        <div class="studentbar--item">
            <p><b>Student ID:</b> @Model.Registration.Student.StudentId</p>
        </div>
        <div class="studentbar--item">
            <p><b>Units:</b> @Model.Registration.Student.TotalUnits</p>
        </div>
        <div class="studentbar--item">
            <p><b>Major(s):</b> @Model.Registration.Student.ActualStrMajors</p>
        </div>
    </div>
</div>

@using (Html.BeginForm("ExtraTicketPetitionNew", "Petition", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="main">
        <div class="main_contents">
            <div class="register">
                <div class="register__section">
                    @Html.ValidationSummary("Please correct all errors below")
                    @for (int j = 0; j < registrations.Count; j++)
                    {
                        var participation = registrations[j];

                        <div class="ceremony">
                            <h2>@participation.Ceremony.CeremonyName</h2>
                            @if (!Model.AvailableParticipationIds.Contains(participation.Id))
                            {
                                var theAlertMessage = string.Empty;
                                if (participation.ExtraTicketPetition != null)
                                {
                                    theAlertMessage = "This ceremony is not available for extra ticket petition because you have previously submitted a petition.";
                                }
                                else if (DateTime.Now < participation.Ceremony.ExtraTicketBegin) //TODO: Fix Date for UTC
                                {
                                    theAlertMessage = string.Format("This ceremony is not available for extra ticket petition.  Please return on {0:d} to submit a petition.", participation.Ceremony.ExtraTicketBegin);
                                }
                                else if (DateTime.Now > participation.Ceremony.ExtraTicketDeadline.AddDays(1)) //TODO: Fix date for UTC
                                {
                                    theAlertMessage = string.Format("This ceremony is not available for extra ticket petitions.  The deadline was on {0:d} ", participation.Ceremony.ExtraTicketDeadline);
                                }
                                <div class="alert alert-danger">
                                    <span>@theAlertMessage</span>
                                </div>
                            }

                            <table cellspacing="10">
                                <tbody>
                                <tr>
                                    <td><b>Major:</b></td>
                                    <td>@Html.DisplayFor(x => participation.Major.Name)</td>
                                </tr>
                                <tr>
                                    <td><b>Ceremony Time:</b></td>
                                    <td>@Html.DisplayFor(x => participation.Ceremony.DateTime)</td>
                                </tr>
                                <tr>
                                    <td><b>Delivery Method:</b></td>
                                    <td>@Html.DisplayFor(x => participation.TicketDistributionMethod.Name)</td>
                                </tr>
                                <tr>
                                    <td><b># Tickets Requested:</b></td>
                                    <td>@Html.DisplayFor(x => participation.NumberTickets)</td>
                                </tr>
                                @if (Model.AvailableParticipationIds.Contains(participation.Id))
                                {
                                    var postModel = Model.ExtraTicketPetitionPostModels.Where(a => a.RegistrationParticipation == participation).FirstOrDefault();                                    

                                    @Html.Hidden(string.Format("extraTicketPetitions[{0}].Ceremony", counter), participation.Ceremony.Id)
                                    @Html.Hidden(string.Format("extraTicketPetitions[{0}].RegistrationParticipation", counter), participation.Id)

                                    <tr>
                                        <td><b>Extra Tickets:</b></td>
                                        <td>
                                            <select id="@string.Format("extraTicketPetitions[{0}]_NumberTickets", counter)" name="@string.Format("extraTicketPetitions[{0}].NumberTickets", counter)" class="long">

                                                <option value="">--Select # of Tickets--</option>

                                                @for (int i = 1; i <= participation.Ceremony.ExtraTicketPerStudent; i++)
                                                {
                                                    <option value="@i" @(postModel != null && i == postModel.NumberTickets ? "selected=\"selected\"" : string.Empty)>@string.Format("{0:00}", i)</option>
                                                }
                                            </select>
                                        </td>
                                    </tr>
                                    if (participation.Ceremony.HasStreamingTickets)
                                    {
                                        <tr>
                                            <td><b>Streaming Tickets:</b></td>
                                            <td>
                                                <select id="@string.Format("extraTicketPetitions[{0}]_NumberStreamingTickets", counter)" name="@string.Format("extraTicketPetitions[{0}].NumberStreamingTickets", counter)" class="long">

                                                    <option value="">--Select # of Tickets--</option>

                                                    @for (int i = 1; i <= participation.Ceremony.ExtraTicketPerStudent; i++)
                                                    {
                                                        <option value="@i" @(postModel != null && i == postModel.NumberStreamingTickets ? "selected=\"selected\"" : string.Empty)>@string.Format("{0:00}", i)</option>
                                                    }
                                                </select>
                                            </td>
                                        </tr>
                                    }
                                    else
                                    {
                                        @Html.Hidden(string.Format("extraTicketPetitions[{0}]_NumberStreamingTickets", counter), 0)
                                    }

                                }


                                </tbody>
                            </table>
                            @if (Model.AvailableParticipationIds.Contains(participation.Id))
                            {
                                <div class="input__group">
                                    <label class="pull-left">Reason</label>
                                    <textarea style="width: 100%" type="text" id="@string.Format("extraTicketPetitions[{0}].Reason", counter)" name="@string.Format("extraTicketPetitions[{0}].Reason", counter)" rows="4" class="petition-reason">@(participation.ExtraTicketPetition != null ? participation.ExtraTicketPetition.Reason : string.Empty)</textarea>
                                    @Html.ValidationMessage("Reason" + participation.Ceremony.Id)
                                </div>
                                counter++;
                            }
                        </div>

                    }
                    <button type="submit" class="btn btn-18 btn-green"><i class="fa fa-graduation-cap" aria-hidden="true"></i> Submit </button>
                    <a href="@Url.Action("DisplayRegistration", "Student")" class="btn btn-18 btn-blue">Cancel</a>
                </div>


            </div>

        </div>

    </div>


}


@section AdditionalScripts
{
    @Scripts.Render("~/bundles/easycounter")
    @Scripts.Render("~/bundles/jqueryval")   
    <script type="text/javascript" src="https://ajax.aspnetcdn.com/ajax/mvc/4.0/jquery.validate.unobtrusive.min.js"></script>

    @*TODO: Fix jquery multiple loads. page validate isn't working would these*@
    <script>
        $(function () {
            $("textarea.petition-reason")
                .jqEasyCounter({
                    'maxChars': 100,
                    'maxCharsWarning': 80,
                    'msgAppendMethod': 'insertBefore',
                    'msgTextAlign': 'right'
                });
        });
    </script>
    


}
